{"body": "\nSorry if this has been already resolved. Tried searching Github discussions no luck.\n\n\n\nI am trying the Bioclimatic Chart but I get the following error (I am still using the example file from the group):\n\n\n\nRuntime error (MissingMemberException): 'NoneType' object has no attribute 'Faces'<br/>Traceback:<br/>\u00a0 line 1642, in main, \"&lt;string&gt;\"<br/>\u00a0 line 1717, in script<br/>\u00a0 line 593, in drawColorResults, \"&lt;string&gt;\"<br/>\u00a0 line 674, in graphResults, \"&lt;string&gt;\"<br/>\u00a0 line 814, in showResults, \"&lt;string&gt;\"<br/><br/>\n\nWould appreciate some assistance.\n\n\n\nKind regards,\n\nTheodore.\n", "attachments": [], "created_by_name": "Theodoros Galanos", "created_at": "February 6, 2015 at 1:54am", "created_by": "TheodorosGalanos", "topic": "Bioclimatic Chart", "replies": [{"body": "\nHi Theodoros,\n\nDo you mind attaching the file you are using?\n\nThe example file is working for me just fine. So my bet is that probably you are mixing old components with new ones. But i need to check.\n\n-A.\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "February 6, 2015 at 7:11am", "created_by": "AbrahamYezioro", "replies": [{"body": "\nSorry for the late reply Abraham.\n\n\n\nHere it is, it is the example file if I'm not mistaken.\n\n\n\nKind regards,\n\nTheodore.\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1220972", "name": "BioclimaticChart.gh"}], "created_by_name": "Theodoros Galanos", "created_at": "February 9, 2015 at 5:28am", "created_by": "TheodorosGalanos", "replies": []}, {"body": "\nI can't replicate the error. The file is working just fine at my end ... :-( or :-)\n\nAre you sure this is the one you are having trouble with?\n\n-A.\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "February 9, 2015 at 5:37am", "created_by": "AbrahamYezioro", "replies": []}, {"body": "\nAbraham,\n\nBased on the error \"meshedC\" doesn't get generated and that's why the code fails in line 593. What could be the case to make this happen? and can we add an extra check for that?\n\nMostapha\n\n\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "February 9, 2015 at 8:22pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nIt also works fine on my system. Which weather file are you using?\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "February 9, 2015 at 8:18pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nHi guys,\n\n\n\nI am using the Kuala Lumpur weather file.\n\n\n\nRegards,\n\nTheodore.\n", "attachments": [], "created_by_name": "Theodoros Galanos", "created_at": "February 9, 2015 at 8:20pm", "created_by": "TheodorosGalanos", "replies": []}, {"body": "\nOK. It fails indeed. I need to check thoroughly.\n\nThe stPt coordinates are messed in the routine (at line 593). For some reason they get crazy values.\n\nI'm checking ...\n\n-A.\n\n\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "February 10, 2015 at 1:50pm", "created_by": "AbrahamYezioro", "replies": []}]}], "id": "1219339"}