{"body": "\nI am updating to the latest (2016) components an excellent example script for external environment UTCI / comfort analysis. It is attached.\n\n\n\nI have it all working except for the very last 2 components: the penultimate one \"Honeybee_Microclimate Map Analysis\" seems to be the problem. This provides output not as a list of numbers but as a list of most of the total list length of 745 not containing the expected data values but code that reads \"IronPython.Runtime.List\" for each line...\n\nThen the final component \"Honeybee_Visulaize Microclimate Map\" gives an error, I presume because of the output from the above component.\n\n\n\nThoughts?\n\n\n\nMy plan is to adapt this to read a GIS file of real building form data, but first I need this working...\n\n\n\nM\n\n\n\n\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1529134", "name": "Outdoor_Microclimate_Map_updateV2a.gh"}], "created_by_name": "Michael Donn", "created_at": "May 12, 2016 at 9:20am", "created_by": "MichaelDonn", "topic": "Odd behaviour of Honeybee_Microclimate Map Analysis?", "replies": [{"body": "\nMichael,\n\nYour update was right. There were many components \"outdated\".\n\nAfter updating it right and reinserting a couple of components your file is working. See attached.\n\n-A.\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1528983", "name": "Outdoor_Microclimate_Map_updateV2a_AY.gh"}], "created_by_name": "Abraham Yezioro", "created_at": "May 12, 2016 at 10:51am", "created_by": "AbrahamYezioro", "replies": [{"body": "\nthanks\n", "attachments": [], "created_by_name": "Michael Donn", "created_at": "April 23, 2017 at 8:52pm", "created_by": "MichaelDonn", "replies": []}]}, {"body": "\nthanks\n", "attachments": [], "created_by_name": "Michael Donn", "created_at": "April 23, 2017 at 8:52pm", "created_by": "MichaelDonn", "replies": []}], "id": "1529135"}