{"body": "\nHello,\n\nI'm getting the following error in the runDaylightAnalysis component, when I connect the skyFilePath from the genCumSky component (image and GH file is attached):\n\n\n\n\"Failed to read the results!<br/>rtrace: skybright`C__Users_vasanthakumars_AppData_Roaming_Ladybug_skylib_cumulativeSkies_Toron_Toron_1: undefined variable\n\nTraceback:\n\nline 336, in script\"\n\n\n\nThe runDaylightAnalysis works when I use the skyFilePath from genClimateBasedSky.\n\n\n\nAlso, FWIW I looked around and noticed that it didn't seem like I had the GenCumalitiveSky.exe, and so I manually downloaded it and inserted into my current working directory and the Radiance folder. \u00a0But this obviously didn't resolve the problem.\u00a0\n\nAnyone knows what's wrong?\u00a0\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1592072", "name": "lb_error.JPG"}, {"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1592073", "name": "hb_radiation_internal_error.gh"}], "created_by_name": "Saeran Vasanthakumar", "created_at": "September 1, 2016 at 12:00pm", "created_by": "SaeranVasanthakumar", "topic": "Error w/ Honeybee runDaylightAnalysis and genCumSky components", "replies": [{"body": "\nUpdate: After downloading the newest release of HB and LB, and trying it on my home machine this issue seems to have disappeared. I need to try it on my work computer to make sure this is completely working, but so far so good!\n", "attachments": [], "created_by_name": "Saeran Vasanthakumar", "created_at": "September 4, 2016 at 1:11am", "created_by": "SaeranVasanthakumar", "replies": [{"body": "\nDid it work?\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "September 11, 2016 at 9:58am", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nUpdate: No it didn't work. So I think there's something going on with the way the skyfile is saved and read in the working directory. I've tried to move the generated file around but its still not working, but I'll ask our IT guys to take a look at this issue to see if they have any insight. \u00a0\n", "attachments": [], "created_by_name": "Saeran Vasanthakumar", "created_at": "September 20, 2016 at 4:00pm", "created_by": "SaeranVasanthakumar", "replies": []}]}, {"body": "\nFinal(?) update: run the cumualtiveSky.bat as an admin.\n\n\n\nSee discussion here:\u00a0[http://www.grasshopper3d.com/group/ladybug/forum/topics/cannot-find...](http://www.grasshopper3d.com/group/ladybug/forum/topics/cannot-find-function-file-1)\n", "attachments": [], "created_by_name": "Saeran Vasanthakumar", "created_at": "October 5, 2016 at 1:58pm", "created_by": "SaeranVasanthakumar", "replies": [{"body": "\nGreat! good to know. we still need to figure out a solution to run it without admin rights.\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "October 9, 2016 at 9:32am", "created_by": "MostaphaSadeghipour", "replies": []}]}], "id": "1592074"}