{"body": "\nThank you Mostapha!\n\nUnfortunately I do have a strange issue when using this sript: it can't find the error.log file.\n\n\n\nThis is the report dialog of the RunDaylightAnalysis component:\n\n**Daylight factor**<br/>**The component is checking ad, as, ar and aa values. This is just to make sure that the results are accurate enough.**<br/>**Good to go!**<br/>**Current working directory is set to: c:\\ladybug\\unnamed\\DF\\**<br/>**Runtime error (FileNotFoundException): Le fichier 'c:\\ladybug\\unnamed\\DF\\error.log' est introuvable.**<br/>**Traceback:**<br/> **line 327, in script**\n\n\n\nI never had this problem before... and I don't see the link between your python component and this error.\n\n\n\n<br/>[<img class=\"align-full\" src=\"http://api.ning.com:80/files/tJGoy4W-urXHZLf1LAj0IZzfStiDz4sFxhZzk63Ww*t3Kf2fPKCeX61I4PW*mic9p6F0kaCS69y3fln-apHZ3H9*RoPsYae-/Capture_error.JPG?width=721\" width=\"721\"/>](http://api.ning.com:80/files/tJGoy4W-urXHZLf1LAj0IZzfStiDz4sFxhZzk63Ww*t3Kf2fPKCeX61I4PW*mic9p6F0kaCS69y3fln-apHZ3H9*RoPsYae-/Capture_error.JPG)\n\n\n", "attachments": [], "created_by_name": "Aymeric", "created_at": "March 29, 2017 at 08:32AM", "created_by": "AymericDELABACHELERIE", "parent_id": "reply_2985220_Comment_1723271", "id": "reply_2985220_Comment_1723288"}